// Generated by dts-bundle-generator v9.5.1

export declare function health(): Promise<{
	status: string;
	timestamp: string;
	db: string;
}>;
export declare function getGigs(isCareer?: boolean): Promise<({
	_count: {
		applications: number;
	};
} & {
	id: string;
	title: string;
	category: string;
	payRate: string;
	location: string;
	description: string;
	posterName: string;
	posterEmail: string;
	isCareer: boolean;
	createdAt: Date;
})[]>;
export declare function getGig(id: string): Promise<({
	_count: {
		applications: number;
	};
} & {
	id: string;
	title: string;
	category: string;
	payRate: string;
	location: string;
	description: string;
	posterName: string;
	posterEmail: string;
	isCareer: boolean;
	createdAt: Date;
}) | null>;
export declare function createGig(data: {
	title: string;
	category: string;
	payRate: string;
	location: string;
	description: string;
	posterName: string;
	posterEmail: string;
	isCareer?: boolean;
}): Promise<{
	id: string;
	title: string;
	category: string;
	payRate: string;
	location: string;
	description: string;
	posterName: string;
	posterEmail: string;
	isCareer: boolean;
	createdAt: Date;
}>;
export declare function applyToGig(gigId: string, message: string): Promise<{
	id: string;
	createdAt: Date;
	gigId: string;
	userId: string;
	message: string;
}>;
export declare function getMyProfile(): Promise<{
	profile: {
		id: string;
		location: string;
		createdAt: Date;
		userId: string;
		bio: string;
		skills: string;
		workHistory: string;
		phone: string;
		updatedAt: Date;
	} | null;
	applications: ({
		gig: {
			id: string;
			title: string;
			category: string;
			payRate: string;
			location: string;
			description: string;
			posterName: string;
			posterEmail: string;
			isCareer: boolean;
			createdAt: Date;
		};
	} & {
		id: string;
		createdAt: Date;
		gigId: string;
		userId: string;
		message: string;
	})[];
}>;
export declare function upsertProfile(data: {
	bio?: string;
	skills?: string;
	workHistory?: string;
	phone?: string;
	location?: string;
}): Promise<{
	id: string;
	location: string;
	createdAt: Date;
	userId: string;
	bio: string;
	skills: string;
	workHistory: string;
	phone: string;
	updatedAt: Date;
}>;
export declare function getHousingListings(type?: string, maxPrice?: number, minBedrooms?: number): Promise<{
	type: string;
	id: string;
	description: string;
	createdAt: Date;
	propertyType: string;
	price: number;
	address: string;
	neighborhood: string;
	bedrooms: number;
	bathrooms: number;
	sqft: number;
	utilitiesIncl: boolean;
	petFriendly: boolean;
	parking: boolean;
	contactName: string;
	contactEmail: string;
}[]>;
export declare function createHousingListing(data: {
	type: string;
	propertyType: string;
	price: number;
	address: string;
	neighborhood?: string;
	bedrooms?: number;
	bathrooms?: number;
	sqft?: number;
	description: string;
	utilitiesIncl?: boolean;
	petFriendly?: boolean;
	parking?: boolean;
	contactName: string;
	contactEmail: string;
}): Promise<{
	type: string;
	id: string;
	description: string;
	createdAt: Date;
	propertyType: string;
	price: number;
	address: string;
	neighborhood: string;
	bedrooms: number;
	bathrooms: number;
	sqft: number;
	utilitiesIncl: boolean;
	petFriendly: boolean;
	parking: boolean;
	contactName: string;
	contactEmail: string;
}>;
export declare function getRestorationProjects(): Promise<({
	_count: {
		laborPledges: number;
		updates: number;
	};
	champion: {
		id: string;
		name: string | null;
		handle: string | null;
	};
} & {
	id: string;
	description: string;
	createdAt: Date;
	address: string;
	city: string;
	status: string;
	proposedUse: string;
	estimatedCost: number;
	fundingGoal: number;
	amountRaised: number;
	backerCount: number;
	championId: string;
})[]>;
export declare function getRestorationProject(id: string): Promise<({
	laborPledges: ({
		user: {
			id: string;
			name: string | null;
			handle: string | null;
		};
	} & {
		id: string;
		createdAt: Date;
		userId: string;
		projectId: string;
		skill: string;
		hours: number;
	})[];
	champion: {
		id: string;
		name: string | null;
		handle: string | null;
	};
	updates: {
		id: string;
		createdAt: Date;
		projectId: string;
		content: string;
	}[];
} & {
	id: string;
	description: string;
	createdAt: Date;
	address: string;
	city: string;
	status: string;
	proposedUse: string;
	estimatedCost: number;
	fundingGoal: number;
	amountRaised: number;
	backerCount: number;
	championId: string;
}) | null>;
export declare function createRestorationProject(data: {
	address: string;
	city: string;
	status: string;
	proposedUse: string;
	estimatedCost: number;
	fundingGoal: number;
	description: string;
}): Promise<{
	id: string;
	description: string;
	createdAt: Date;
	address: string;
	city: string;
	status: string;
	proposedUse: string;
	estimatedCost: number;
	fundingGoal: number;
	amountRaised: number;
	backerCount: number;
	championId: string;
}>;
export declare function pledgeLabor(projectId: string, skill: string, hours: number): Promise<{
	id: string;
	createdAt: Date;
	userId: string;
	projectId: string;
	skill: string;
	hours: number;
}>;
export declare function addRestorationUpdate(projectId: string, content: string): Promise<{
	id: string;
	createdAt: Date;
	projectId: string;
	content: string;
}>;
export declare function seedHousing(): Promise<{
	seeded: boolean;
	message: string;
} | {
	seeded: boolean;
	message?: undefined;
}>;
export declare function rateUser(toUserId: string, score: number, comment: string, gigId?: string): Promise<{
	id: string;
	createdAt: Date;
	gigId: string | null;
	fromUserId: string;
	toUserId: string;
	score: number;
	comment: string;
}>;
export declare function getUserRatings(userId: string): Promise<{
	ratings: ({
		fromUser: {
			id: string;
			name: string | null;
			image: string | null;
			handle: string | null;
		};
	} & {
		id: string;
		createdAt: Date;
		gigId: string | null;
		fromUserId: string;
		toUserId: string;
		score: number;
		comment: string;
	})[];
	average: number | null;
	count: number;
}>;
export declare function reportUser(targetUserId: string, reason: string): Promise<{
	id: string;
	createdAt: Date;
	reporterId: string;
	targetUserId: string | null;
	targetListingId: string | null;
	reason: string;
}>;
export declare function reportListing(targetListingId: string, reason: string): Promise<{
	id: string;
	createdAt: Date;
	reporterId: string;
	targetUserId: string | null;
	targetListingId: string | null;
	reason: string;
}>;
export declare function blockUser(blockedId: string): Promise<{
	id: string;
	createdAt: Date;
	blockerId: string;
	blockedId: string;
}>;
export declare function getBlockedUsers(): Promise<string[]>;
export declare function getOrCreateConversation(otherUserId: string): Promise<{
	user1: {
		id: string;
		name: string | null;
		image: string | null;
		handle: string | null;
	};
	user2: {
		id: string;
		name: string | null;
		image: string | null;
		handle: string | null;
	};
} & {
	id: string;
	createdAt: Date;
	updatedAt: Date;
	participant1: string;
	participant2: string;
}>;
export declare function getConversations(): Promise<{
	id: string;
	otherUser: {
		id: string;
		name: string | null;
		image: string | null;
		handle: string | null;
	};
	lastMessage: {
		id: string;
		createdAt: Date;
		content: string;
		conversationId: string;
		senderId: string;
		read: boolean;
	};
	unreadCount: number;
	updatedAt: Date;
}[]>;
export declare function getMessages(conversationId: string): Promise<({
	sender: {
		id: string;
		name: string | null;
		image: string | null;
		handle: string | null;
	};
} & {
	id: string;
	createdAt: Date;
	content: string;
	conversationId: string;
	senderId: string;
	read: boolean;
})[]>;
export declare function sendMessage(conversationId: string, content: string): Promise<{
	sender: {
		id: string;
		name: string | null;
		image: string | null;
		handle: string | null;
	};
} & {
	id: string;
	createdAt: Date;
	content: string;
	conversationId: string;
	senderId: string;
	read: boolean;
}>;
export declare function markMessagesRead(conversationId: string): Promise<{
	success: boolean;
}>;
export declare function getUnreadCount(): Promise<{
	count: number;
}>;
export declare function seedGigs(): Promise<{
	seeded: boolean;
	message: string;
	count?: undefined;
} | {
	seeded: boolean;
	count: number;
	message?: undefined;
}>;

export {};
