// Generated by dts-bundle-generator v9.5.1

export declare function health(): Promise<{
	status: string;
	timestamp: string;
	db: string;
}>;
export declare function getGigs(isCareer?: boolean): Promise<({
	_count: {
		applications: number;
	};
} & {
	id: string;
	title: string;
	category: string;
	payRate: string;
	location: string;
	description: string;
	posterName: string;
	posterEmail: string;
	isCareer: boolean;
	createdAt: Date;
})[]>;
export declare function getGig(id: string): Promise<({
	_count: {
		applications: number;
	};
} & {
	id: string;
	title: string;
	category: string;
	payRate: string;
	location: string;
	description: string;
	posterName: string;
	posterEmail: string;
	isCareer: boolean;
	createdAt: Date;
}) | null>;
export declare function createGig(data: {
	title: string;
	category: string;
	payRate: string;
	location: string;
	description: string;
	posterName: string;
	posterEmail: string;
	isCareer?: boolean;
}): Promise<{
	id: string;
	title: string;
	category: string;
	payRate: string;
	location: string;
	description: string;
	posterName: string;
	posterEmail: string;
	isCareer: boolean;
	createdAt: Date;
}>;
export declare function applyToGig(gigId: string, message: string): Promise<{
	id: string;
	createdAt: Date;
	gigId: string;
	userId: string;
	message: string;
}>;
export declare function getMyProfile(): Promise<{
	profile: {
		id: string;
		location: string;
		createdAt: Date;
		userId: string;
		bio: string;
		skills: string;
		workHistory: string;
		phone: string;
		updatedAt: Date;
	} | null;
	applications: ({
		gig: {
			id: string;
			title: string;
			category: string;
			payRate: string;
			location: string;
			description: string;
			posterName: string;
			posterEmail: string;
			isCareer: boolean;
			createdAt: Date;
		};
	} & {
		id: string;
		createdAt: Date;
		gigId: string;
		userId: string;
		message: string;
	})[];
}>;
export declare function upsertProfile(data: {
	bio?: string;
	skills?: string;
	workHistory?: string;
	phone?: string;
	location?: string;
}): Promise<{
	id: string;
	location: string;
	createdAt: Date;
	userId: string;
	bio: string;
	skills: string;
	workHistory: string;
	phone: string;
	updatedAt: Date;
}>;
export declare function seedGigs(): Promise<{
	seeded: boolean;
	message: string;
	count?: undefined;
} | {
	seeded: boolean;
	count: number;
	message?: undefined;
}>;

export {};
